server {
    listen 80;
    
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # LA LÍNEA MÁGICA: Si no encuentras el archivo, redirige a index.html
        try_files $uri $uri/ /index.html;
    }
}